// manifest.js (auto-generated 2026-03-12)
window.decks = [
  "Alignment_Problem.js",
  "ML101.js",
  "amodeietal01.js",
  "amodeietal02.js",
  "analogy.js",
  "christianAlignmentProblem01.js",
  "collins01.js",
  "collins02.js",
  "controlOversight.js",
  "deterrence.js",
  "ethics101.js",
  "ethicsShort.js",
  "governance.js",
  "jobinetal2019.js",
  "ml4h_p1.js",
  "ml4h_p21.js",
  "modelCards.js",
  "offSwitch.js",
  "sillyRules.js",
  "socialOrderVocabulary.js",
  "virtueEthics.js",
  "whyBureaucracy.js",
];
